PLAYER_COUNT = 6

FRICTION = 5
MAX_PLAYER_SPEED = 10
MAX_KICK_POWER = 60


# RULES
ALLOWED_PLAYERS_IN_PENALTY_AREA_NUMBER = 3
ALLOWED_PLAYERS_AROUND_BALL_NUMBER = 1
ALLOWED_PLAYERS_AROUND_BALL_RADIUS =  54
BALL_CROWDED_BAN_CYCLES = 25
PENALTY_ARIA_BAN_CYCLES = 20
