FOOTBALL_PITCH_WIDTH = 1000
FOOTBALL_PITCH_HEIGHT = 650

PLAYER_RADIUS = 10
PLAYER_NUMBER_FONT_SIZE = 20
PLAYER_NAME_FONT_SIZE = 16
BALL_RADIUS = 8

VERTICAL_MARGIN = 46
HORIZONTAL_MARGIN = 46

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 742


# FOOTBALL PITCH
GOAL_WIDTH = 196
GOAL_DEPTH = 24
CENTER_POINT_RADIUS = 4
CENTER_CIRCLE_RADIUS = 92
LINE_THICKNESS = 4
PENALTY_AREA_HEIGHT = 326
PENALTY_AREA_WIDTH = 200


# SCOREBOARD
SCOREBOARD_FONT_SIZE = 40
